export enum ReconciliationMode {
  FULL_CHECK = 'FULL_CHECK',
  LABELED_CHECK = 'LABELED_CHECK',
  DATE_RANGE_CHECK = 'DATE_RANGE_CHECK',
  FILTERED_CHECK = 'FILTERED_CHECK',
  INCREMENTAL_CHECK = 'INCREMENTAL_CHECK',
}
