export const RECONCILIATION_MODULE_OPTIONS = 'RECONCILIATION_MODULE_OPTIONS';
export const TO_COMPARABLE_STATE = 'TO_COMPARABLE_STATE';
export const AGGREGATE_ROOT = 'AGGREGATE_ROOT';
export const AGGREGATE_NAME = 'AGGREGATE_NAME';
export const STATE_COMPARATOR = 'STATE_COMPARATOR';
export const AGGREGATE_RECONSTRUCTOR = 'AGGREGATE_RECONSTRUCTOR';
export const RECONCILIATION_SERVICE_PORT = 'ReconciliationServicePort';
export const EVENT_TRANSFORMERS = 'EVENT_TRANSFORMERS';
