export const RECO_MODULE_OPTIONS = 'RECO_MODULE_OPTIONS';
export const WRITE_REPOSITORY = 'WRITE_REPOSITORY';
export const TO_COMPARABLE_STATE = 'TO_COMPARABLE_STATE';
export const AGGREGATE_ROOT = 'AGGREGATE_ROOT';
export const STATE_COMPARATOR = 'STATE_COMPARATOR';
export const AGGREGATE_RECONSTRUCTOR = 'AGGREGATE_RECONSTRUCTOR';
export const RECO_SERVICE_PORT = 'RecoServicePort';
